{
    "openapi": "3.0.0",
    "info": {
      "title": "Tickets API",
      "version": "1.0.0",
      "description": "Projeto Integrador FAP Backend - Tickets API"
    },
    "servers":[                  
        {
            "url":"https://softex-tickets-api.onrender.com",
            "description": "API em deploy no render"
        }        
    ],
    "paths":{
        "/user/create":{
            "post":{
                "summary":"Cadastrar Usuário",
                "description":"Rota para cadastro de usuários",
                "tags":["User"],
                "requestBody":{
                    "content":{
                        "application/json":{
                            "schema":{
                                "$ref":"#/components/schemas/User"
                            },
                            "examples":{
                                "ADMIN":{
                                    "value":{
                                        "name":"Roberto Carlos",
                                        "email":"emailexemplo@gmail.com",                                        
                                        "phone":"999999999",
                                        "password":"123",
                                        "role":"ADMIN",
                                        "commenterText":"Exemplo"
                                    }
                                },
                                "AGENT":{
                                    "value":{
                                        "name":"Amado Batista",
                                        "email":"emailexemplo2@gmail.com",                                        
                                        "phone":"8888888888",
                                        "password":"123",
                                        "role":"AGENT",
                                        "commenterText":"Exemplo"
                                    }
                                },
                                "CUSTOMER":{
                                    "value":{
                                        "name":"Reginaldo Rossi",
                                        "email":"emailexemplo3@gmail.com",                                        
                                        "phone":"8888888888",
                                        "password":"123",
                                        "role":"CUSTOMER",
                                        "commenterText":"Exemplo"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses":{
                    "201":{
                        "description":"Usuário criado com sucesso"
                    },
                    "409":{
                        "description":"O endereço de e-mail já está em uso por outro usuário."
                    },
                    "400":{
                        "description":"Erro ao criar usuário"
                    }
                }
            }
        },
        "/login":{
            "post":{
                "summary":"Login de Usuário",
                "description":"Rota para Login de usuário",
                "tags":["Login"],
                "requestBody":{
                    "content":{
                        "application/json":{
                            "schema":{
                                "$ref":"#/components/schemas/Login"
                            },
                            "examples":{
                                "Login":{
                                    "value":{                                        
                                        "email":"emailexemplo@gmail.com",                                     
                                        "password":"123"  
                                    }
                                }
                            }
                        }
                    }
                },
                "responses":{
                    "200":{
                        "description":"Login realizado com sucesso!"
                    },
                    "401":{
                        "description":"Usuário ou Senha inválidos!"
                    },
                    "500":{
                        "description":"Erro na autenticação de usuário"
                    }
                }
            }                
        },
        "/categories":{
            "get":{
                "summary":"Listagem de Categorias",
                "description":"Rota para Listagem de Categorias",
                "tags":["Categorias"],
                "security":[{"bearerAuth":[]}],
                "responses":{
                    "200":{
                        "description":"Success"
                    },                    
                    "400":{
                        "description":"Error to get categories"
                    }
                }
            },
            "post":{
                "summary":"Criação de Categorias",
                "description":"Rota para Criação de Categorias",
                "tags":["Categorias"],
                "security":[{"bearerAuth":[]}],
                "requestBody":{
                    "content":{
                        "application/json":{
                            "schema":{
                                "$ref":"#/components/schemas/Categorias"
                            },
                            "examples":{
                                "Catedoria":{
                                    "value":{                                        
                                        "name":"TI",                                     
                                        "description":"Departamento de TI",
                                        "commenter_text":"Manutenção em Computadores"  
                                    }
                                }
                            }
                        }
                    }
                },
                "responses":{
                    "201":{
                        "description":"Category created!"
                    },                    
                    "500":{
                        "description":"Internal server error!"
                    }
                }
            }                            
        },
        "/category/{id}":{
            "patch":{
                "summary":"Atualização de Categorias",
                "description":"Rota para Atualização de Categorias",
                "tags":["Categorias"],
                "security":[{"bearerAuth":[]}],
                "parameters":[{
                    "name":"id",
                    "in":"path",
                    "description":"ID da categoria para atualização",
                    "required":true
                }],
                "requestBody":{
                    "content":{
                        "application/json":{                           
                            "examples":{
                                "Catedoria":{
                                    "value":{                                        
                                        "name":"TI",                                     
                                        "description":"Departamento de Tecnologia da Informação"                                          
                                    }
                                }
                            }
                        }
                    }
                },
                "responses":{
                    "200":{
                        "description":"Category updated"
                    },                    
                    "500":{
                        "description":"Internal server error!"
                    }
                }
            },
            "delete":{
                "summary":"Deletar Categoria",
                "description":"Rota para Deletar Categoria",
                "tags":["Categorias"],
                "security":[{"bearerAuth":[]}],
                "parameters":[{
                    "name":"id",
                    "in":"path",
                    "description":"ID da categoria para atualização",
                    "required":true
                }],                
                "responses":{
                    "200":{
                        "description":"Category updated"
                    },                    
                    "500":{
                        "description":"Internal server error!"
                    }
                }
            }
        },
        "/ticket/create":{
            "post":{
                "summary":"Criação de Tickets",
                "description":"Rota para Criação de Tickets",
                "tags":["Tickets"],
                "security":[{"bearerAuth":[]}],
                "requestBody":{
                    "content":{
                        "application/json":{
                            "schema":{
                                "$ref":"#/components/schemas/Tickets"
                            },
                            "examples":{
                                "Ticket":{
                                    "value":{                                        
                                        "title":"Formatar Notebook",                                     
                                        "description":"Por favor Formatar Notebook do escritório",
                                        "category_id":1  
                                    }
                                }
                            }
                        }
                    }
                },
                "responses":{
                    "201":{
                        "description":"Ticket criado com sucesso!"
                    },                    
                    "400":{
                        "description":"Erro ao criar ticket"
                    }
                }
            }                
        },
        "/ticket/view/{status}":{
            "get":{
                "summary":"Listagem de Tickets",
                "description":"Rota para Listagem de Tickets",
                "tags":["Tickets"],
                "security":[{"bearerAuth":[]}],
                "parameters":[{
                    "name":"status",
                    "in":"path",
                    "description":"Status do Ticket",                    
                    "examples":{
                        "ALL": {
                            "value": "",
                            "summary": "ALL"
                          },
                          "OPEN": {
                            "value": "OPEN",
                            "summary": "OPEN"
                          },
                          "IN_PROGRESS": {
                            "value": "IN_PROGRESS",
                            "summary": "IN_PROGRESS"
                          },
                          "RESOLVED": {
                            "value": "RESOLVED",
                            "summary": "RESOLVED"
                          },
                          "CLOSED": {
                            "value": "CLOSED",
                            "summary": "CLOSED"
                          }
                    }
                }],                
                "responses":{
                    "200":{
                        "description":"Success"
                    },                    
                    "404":{
                        "description":"Nenhum Ticket com Status pesquisado"
                    },
                    "400":{
                        "description":"Erro ao Listar Tickets!"
                    }
                }
            }                
        },
        "/ticket/assigneeAgentTicket/{ticket_id}":{
            "patch":{
                "summary":"Atribuir AGENT logado ao Ticket",
                "description":"Rota para atribuir AGENT logado ao Ticket",
                "tags":["Tickets"],
                "security":[{"bearerAuth":[]}],
                "parameters":[{
                    "name":"ticket_id",
                    "in":"path",
                    "description":"ID do Ticket",
                    "required":true
                }],                
                "responses":{
                    "200":{
                        "description":"Success"
                    },
                    "404":{
                        "description":"Ticket não encontrado!"
                    },                    
                    "400":{
                        "description":"Erro ao atribuir Ticket ao AGENT!"
                    }
                }
            }
        },
        "/ticket/updateStatusTicket/{ticket_id}":{
            "patch":{
                "summary":"Atualização de Status do Ticket",
                "description":"Rota para Atualização de Status do Ticket",
                "tags":["Tickets"],
                "security":[{"bearerAuth":[]}],
                "parameters":[{
                    "name":"ticket_id",
                    "in":"path",
                    "description":"ID do Ticket",
                    "required":true
                }],
                "requestBody":{
                    "content":{
                        "application/json":{                            
                            "examples":{
                                "RESOLVED":{
                                    "value":{                                        
                                        "status":"RESOLVED"
                                    }
                                },
                                "CLOSED":{
                                    "value":{                                        
                                        "status":"CLOSED"
                                    }
                                },
                                "IN_PROGRESS":{
                                    "value":{                                        
                                        "status":"IN_PROGRESS"
                                    }
                                }
                            }
                        }
                    }
                },                
                "responses":{
                    "200":{
                        "description":"Success"
                    },
                    "404":{
                        "description":"Ticket não encontrado!"
                    },
                    "403":{
                        "description":"Usuário não tem permissão para atualizar o ticket!"
                    },                    
                    "400":{
                        "description":"Erro ao atribuir Ticket ao AGENT!"
                    }
                }
            }
        },
        "/ticket/deleteTicket/{ticket_id}":{
            "delete":{
                "summary":"ADMIN deletar Ticket",
                "description":"Rota para ADMIN deletar Ticket",
                "tags":["Tickets"],
                "security":[{"bearerAuth":[]}],
                "parameters":[{
                    "name":"ticket_id",
                    "in":"path",
                    "description":"ID do Ticket",
                    "required":true
                }],                
                "responses":{
                    "200":{
                        "description":"Success"
                    },
                    "404":{
                        "description":"Ticket não encontrado!"
                    },                    
                    "403":{
                        "description":"Você não tem premissão de ADMIN para deleter o Ticket!"
                    }
                }
            }
        },
        "/tickets/{ticketId}/comments":{
            "post":{
                "summary":"Criação de comentário no ticket",
                "description":"Rota para Criação de comentário no ticket",
                "tags":["Comments"],
                "security":[{"bearerAuth":[]}],
                "parameters":[{
                    "name":"ticketId",
                    "in":"path",
                    "description":"ID do Ticket",
                    "required":true
                }],
                "requestBody":{
                    "content":{
                        "application/json":{
                            "schema":{
                                "$ref":"#/components/schemas/Comments"
                            },
                            "examples":{
                                "Comment":{
                                    "value":{                                        
                                        "commenter_text":"O Notebook será formatado na sexta."     
                                    }
                                }
                            }
                        }
                    }
                },
                "responses":{
                    "201":{
                        "description":"Comment created"
                    },                    
                    "400":{
                        "description":"Internal server error"
                    }
                }
            }                
        },
        "/tickets/comments/{ticketId}":{
            "get":{
                "summary":"Listagem de comentários no ticket",
                "description":"Rota para Listagem de comentários no ticket",
                "tags":["Comments"],
                "security":[{"bearerAuth":[]}],
                "parameters":[{
                    "name":"ticketId",
                    "in":"path",
                    "description":"ID do Ticket",
                    "required":true
                }],                
                "responses":{
                    "200":{
                        "description":"Success"
                    },                    
                    "500":{
                        "description":"Internal server error"
                    }
                }
            }                
        },
        "/tickets/{ticketId}/comments/{commentId}":{
            "patch":{
                "summary":"Atualização de comentário no ticket",
                "description":"Rota para Atualização de comentário no ticket",
                "tags":["Comments"],
                "security":[{"bearerAuth":[]}],
                "parameters":[{
                    "name":"ticketId",
                    "in":"path",
                    "description":"ID do Ticket",
                    "required":true
                },
                {
                    "name":"commentId",
                    "in":"path",
                    "description":"ID do Comentário",
                    "required":true
                }],
                "requestBody":{
                    "content":{
                        "application/json":{
                            "schema":{
                                "$ref":"#/components/schemas/Comments"
                            },
                            "examples":{
                                "Comment":{
                                    "value":{                                        
                                        "commenter_text":"O Notebook será formatado na Segunda."     
                                    }
                                }
                            }
                        }
                    }
                },
                "responses":{
                    "200":{
                        "description":"Comment updated"
                    },
                    "400":{
                        "description":"Comment not found"
                    },
                    "401":{
                        "description":"Unauthorized"
                    },                    
                    "500":{
                        "description":"Internal server error"
                    }
                }
            }                
        },
        "/tickets/comments/{ticketId}/{commentId}":{
            "delete":{
                "summary":"Remoção de comentário no ticket",
                "description":"Rota para Remoção de comentário no ticket",
                "tags":["Comments"],
                "security":[{"bearerAuth":[]}],
                "parameters":[{
                    "name":"ticketId",
                    "in":"path",
                    "description":"ID do Ticket",
                    "required":true
                },
                {
                    "name":"commentId",
                    "in":"path",
                    "description":"ID do Comentário",
                    "required":true
                }],                
                "responses":{
                    "200":{
                        "description":"Comment deleted"
                    },
                    "400":{
                        "description":"Comment not found"
                    },
                    "401":{
                        "description":"Unauthorized"
                    },                    
                    "500":{
                        "description":"Internal server error"
                    }
                }
            }                
        }
    },
    "components":{
        "schemas":{
            "User":{
                "type":"object",
                "properties":{
                    "name":{
                        "type":"string"
                    },
                    "email":{
                        "type":"string"
                    },
                    "phone":{
                        "type":"string"
                    },
                    "password":{
                        "type":"string"
                    },
                    "role":{
                        "type":"string"
                    },
                    "commenterText":{
                        "type":"string"
                    }
                }
            },
            "Login":{
                "type":"object",
                "properties":{
                    "email":{
                        "type":"string"
                    },
                    "password":{
                        "type":"string"
                    }
                }
            },
            "Categorias":{
                "type":"object",
                "properties":{
                    "name":{
                        "type":"string"
                    },
                    "description":{
                        "type":"string"
                    },
                    "commenter_text":{
                        "type":"string"
                    }
                }
            },
            "Tickets":{
                "type":"object",
                "properties":{
                    "title":{
                        "type":"string"
                    },
                    "description":{
                        "type":"string"
                    },
                    "category_id":{
                        "type":"integer"
                    }
                }
            },
            "Comments":{
                "type":"object",
                "properties":{
                    "commenter_text":{
                        "type":"string"
                    },
                    "ticketId":{
                        "type":"integer"
                    },
                    "commenter_id":{
                        "type":"integer"
                    }
                }
            }
        },
        "securitySchemes":{
            "bearerAuth":{
                "type":"http",
                "scheme":"bearer",
                "bearerFormat":"JWT"
            }
        }
    }
}